# -*- coding: utf-8 -*-
"""excersise xp ninga

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10XUqeGs6aq7E3HXanFrzCIXVk9wjNr-G

exercise: Analysis of Diet Effects on GrowthObjective: Conduct a detailed statistical analysis to understand how different diets impact the growth of chicks.Dataset: The dataset consists of information about the weight and age of chicks on different diets. It is available on Kaggle: Weight vs Age of Chicks on Different DietsTasks to Perform:Data Exploration: Examine the dataset to understand its structure and contents. Identify key variables such as age, weight, and diet type.Data Visualization: Create visualizations to show how weight varies with age for chicks on different diets.Statistical Testing: Use appropriate statistical tests (e.g., ANOVA) to determine if the differences in weight gain among the different diets are statistically significant.Growth Analysis: Analyze the growth rate of chicks under different dietary conditions.Report Findings: Compile your findings into a comprehensive report that includes both the statistical analysis and practical implications.Tools and Techniques:Use Python libraries like Pandas for data manipulation.Employ Matplotlib or Seaborn for visualization.Apply statistical methods using SciPy.Expected Outcome:A detailed report that provides insights into the effectiveness of different diets on the growth of chicks, supported by statistical evidence.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import numpy as np
import plotly.express as px
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import numpy as np
import plotly.express as px
import kagglehub
path =kagglehub.dataset_download("lsind18/weight-vs-age-of-chicks-on-different-diets")
data = pd.read_csv(path+"/weight-vs-age.csv")
print(data.head())
print(data.info())
print(data.describe())
plt.figure(figsize=(10, 6))
sns.scatterplot(x='age', y='weight', hue='diet', data=data)
plt.title('Weight vs. Age of Chicks on Different Diets')
plt.xlabel('Age')
plt.ylabel('Weight')
plt.show()
diet_groups = data.groupby('diet')['weight']

fvalue, pvalue = stats.f_oneway(*[group.values for name, group in diet_groups])

print(f"ANOVA results: F-value = {fvalue:.2f}, P-value = {pvalue:.3f}")
alpha = 0.05
if pvalue < alpha:
  print("There is a statistically significant difference in weight among different diets.")
else:
  print("There is no statistically significant difference in weight among different diets.")

data['time_diff'] = data.groupby('chick_id')['age'].diff()

data['growth_rate'] = (data['weight'].diff() / data['time_diff'])

growth_rates_by_diet = data.groupby('diet')['growth_rate'].mean()
print("\nAverage growth rate per diet:")
print(growth_rates_by_diet)

plt.figure(figsize=(8, 6))
sns.boxplot(x='diet', y='growth_rate', data=data)
plt.title('Distribution of Growth Rates by Diet')
plt.xlabel('Diet')
plt.ylabel('Growth Rate')
plt.show()

from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey_result = pairwise_tukeyhsd(data['weight'], data['diet'], alpha=0.05)

print("\nTukey HSD Post-Hoc Test:")
print(tukey_result)
print(data.describe())